"use client";

import { motion } from "framer-motion";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-transparent py-20 px-4">
      <div className="container mx-auto max-w-4xl">
        <motion.div
           initial={{ opacity: 0, y: 20 }}
           animate={{ opacity: 1, y: 0 }}
           transition={{ duration: 0.5 }}
           className="bg-white/80 dark:bg-gray-900/80 backdrop-blur-md rounded-2xl shadow-xl p-8 md:p-12 border border-white/20"
        >
          <h1 className="text-3xl md:text-4xl font-bold mb-8 text-gray-900 dark:text-white border-b border-gray-200 dark:border-gray-800 pb-6">
            Terms of Service
          </h1>

          <div className="space-y-8 text-gray-600 dark:text-gray-300">
            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
              <p className="leading-relaxed">
                By accessing and using VitalSense AI, you accept and agree to be bound by the terms and provision of this agreement.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-red-600 dark:text-red-500 mb-3">2. Medical Disclaimer</h2>
              <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <p className="leading-relaxed text-red-800 dark:text-red-200 font-medium">
                  VitalSense AI is a demonstration tool based on statistical machine learning models. It is NOT a medical device and should NOT be used as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. Accuracy of Information</h2>
              <p className="leading-relaxed">
                While we strive to use high-quality data and algorithms, the predictions generated by this tool may be inaccurate. We accept no liability for any actions taken based on the information provided by this tool.
              </p>
            </section>

             <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">4. Intellectual Property</h2>
              <p className="leading-relaxed">
                Review the source code license for usage rights. This project is intended for educational and portfolio purposes.
              </p>
            </section>

          </div>
        </motion.div>
      </div>
    </div>
  );
}
